openfisca/openfisca.org

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
=> Add Catalonia to available country packages

layouts/_default/countries.html, tests/integration/CountriesComponent.js
Connected to openfisca/openfisca-ops#13
Update the legislation explorer link to fr.legislation.org/legislation
=> Update legislation explorer link

config.toml, layouts/partials/footer.html
=> Add link to status.openfisca.org in footer

content/news/2018-10-08-news.en.md, content/news/2018-10-08-news.fr.md
=> Latest developments 2018-10-08

content/news/2018-10-17-news.en.md, content/news/2018-10-17-news.fr.md
Add `/news/2018-10-17-news` in french and english.
Note: See demo slides [here](https://docs.google.com/presentation/d/1jnZuEbOsfs9x6_vr7r7T9tSQuOJ0aziF7ijuKJtZsYg/edit?usp=sharing).
=> Add latest news from Oct 17th demo

content/news/2018-10-17-news.en.md
=> Fix a country name

layouts/_default/countries.html, layouts/index.html
Link broken issue reported by email on Nov 5 2018
=> Update links towards doc

content/news/2018-10-08-news.en.md, content/news/2018-10-08-news.fr.md, content/news/2018-10-17-news.en.md, content/news/2018-10-17-news.fr.md, layouts/_default/news.html, layouts/_default/post.html
=> Add news list page

content/news/2019-01-16-news.en.md, content/news/2019-01-16-news.fr.md
Adds english and french news files for January 16th demo.
=> Add news for last January 16th demo

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
Connected to #32 
* Add Barcelona name to countries list
* Add link to GitHub repository
=> Add Barcelona model to models list

.circleci/config.yml, tests/integration/config-ci.js
Fixes #62 
Connected to #32 
Look for a solution to fix continuous integration testing.
It [failed](https://circleci.com/gh/openfisca/openfisca.org/690) on master branch.
=> Fix continuous integration tests

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
Connected to #32
* Add Aotearoa New Zealand section to countries page
* Add link to explorer and GitHub repository
=> Add Aotearoa New Zealand to models list

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
Connected to #32
* Add Italy section to countries page
* Add link to GitHub repository
=> Add Italy to models list

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
Connected to #32
* Add New South Wales section to models page
* Add link to GitHub repository
=> Add Australia NSW to models list

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
=> Adding reference to the Uruguay country package

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
=> Add Mali country package

content/countries.en.md, content/countries.fr.md, layouts/_default/countries.html, static/css/countries.css
=> Add Ivory Coast country package

content/countries.en.md
=> Fix name of Côte d'Ivoire

layouts/_default/countries.html
=> Add NSW Legislation Explorer

content/legal-notice.en.md, content/legal-notice.fr.md, layouts/_default/legal-notice.html
I added ANCT details to the legal mentions.
=> Update editor details

layouts/_default/countries.html
Supersedes #87 
Same content but fixes the CI error message.
=> Update Uruguayan package link

config/_default/menus.fr.yaml, content/showcase.fr.md
Improve the french wording for `showcase`.
=> Improve showcase french translation

CONTRIBUTING.md, data/showcase/legislation_explorer.yml, data/showcase/les_meves_ajudes.yml, data/showcase/leximpact.yml, data/showcase/rapu_ture.yml, package-lock.json, package.json, test/showcase/schema.js
This changeset add validation for `source` metadata for reuses.
=> Add source metadata to reuses

data/packages/barcelona.yml
Source: https://fr.wikipedia.org/wiki/ISO_3166-2:ES
=> Use ISO 3166-2 for Barcelona scope

CONTRIBUTING.md, config/_default/params.yaml, data/showcase/les_meves_ajudes.yml, data/showcase/leximpact_impot_revenu.yml, data/showcase/leximpact_socio_fiscal.yml, data/showcase/mes_aides.yml, data/showcase/rapu_ture.yml
Name properly state institutions outside from the executive branch, as per https://github.com/openfisca/openfisca.org/pull/132#discussion_r1099286013.
=> Rename categories “government” to “institution”

config/_default/params.yaml
Fix missing icon for author type `research_center`
=> Fix missing icon

content/tracking.en.md, content/tracking.fr.md, themes/OpenFisca-2022/layouts/partials/footer.html
That changeset:
- add Matomo tracking code
- update Matomo opt-out code
=> Add tracking

data/showcase/dotations_locales.yml
=> Fix typo and make English more idiomatic in Dotations locales

content/association/_index.en.md, content/association/_index.fr.md
- Add names of all members of the board
- Improve readability of Governance section
- Add RNA and SIRET association identification numbers
=> Update board members list
